import { getNextSwissPairings } from '../utils/swissEngine';
import { sortStandings } from '../utils/tournamentStandings';
import { formatMoney } from '../utils/helpers';

function MatchResult({ match, userTeamId }) { if (!match) return null; const maps = match.maps.map(m=>`${m.mapName} ${m.scoreA}-${m.scoreB}`).join(', '); const user = match.teamA.teamId===userTeamId || match.teamB.teamId===userTeamId; return <div className={`match-card ${user?'your-match-card':''}`}><div className="match-line"><strong>{match.teamA.shortName}</strong><span>{match.seriesScore}</span><strong>{match.teamB.shortName}</strong></div><div className="muted">{match.winner.name} won. {match.upset && <b className="upset-tag">UPSET</b>}</div><div className="muted">{maps}</div><div className="muted">Top performer: {match.topPerformer?.gamertag} ({match.topPerformer?.rating})</div><p className="muted">{match.winner.name} beat {match.loser.name} {match.seriesScore} after {maps}. {match.topPerformer?.gamertag} led the server.</p></div> }

export default function EventHub({ gameState, updateTournament }) {
  const t = gameState.activeTournamentState;
  if (!t) return <div><div className="page-header"><h1>Event Hub</h1><div className="subtitle">No active career event.</div></div></div>;
  const userTeamId = gameState.selectedTeamId; const pairings = !t.swiss.complete ? getNextSwissPairings(t.swiss) : [];
  const pendingUser = pairings.find(([a,b]) => [a.teamId,b.teamId].includes(userTeamId));
  const userAlive = t.swiss.standings.find(r=>r.teamId===userTeamId)?.status !== 'eliminated';
  const summary = gameState.completedEvents.find(e=>e.eventId===t.event.eventId);
  return <div><div className="event-hero"><div><h1>{t.event.name}</h1><p>{t.event.eventType} · {formatMoney(t.event.prizePool)} · {t.teams.length} teams · Current stage: {t.champion?'Champion':t.playoffs?'Playoffs':'Swiss'}</p></div><strong>Your team highlighted</strong></div>
  {!t.swiss.complete && <div className="panel"><div className="panel-header"><h2>Swiss Round {t.swiss.rounds.length + 1}</h2><button onClick={()=>updateTournament('swiss-round')}>Auto Sim Remaining Round</button></div><div className="panel-body"><h3>Your Match</h3><div className="match-grid">{pendingUser ? <div className="match-card your-match-card"><div className="match-line"><strong>{pendingUser[0].team.shortName}</strong><span>vs</span><strong>{pendingUser[1].team.shortName}</strong></div><button onClick={()=>updateTournament('swiss-match',{teamAId:pendingUser[0].teamId, teamBId:pendingUser[1].teamId})}>Play / Sim Your Match</button></div> : <div className="muted">No active user match this round.</div>}</div><h3>Other Matches</h3><div className="match-grid">{pairings.filter(p=>p!==pendingUser).map(([a,b])=><div className="match-card" key={a.teamId+b.teamId}><div className="match-line"><strong>{a.team.shortName}</strong><span>vs</span><strong>{b.team.shortName}</strong></div><button onClick={()=>updateTournament('swiss-match',{teamAId:a.teamId, teamBId:b.teamId})}>Sim Other Match</button></div>)}</div></div></div>}
  {t.swiss.complete && !t.playoffs && <button onClick={()=>updateTournament('playoffs')}>Generate Playoffs</button>}
  {t.playoffs && <div className="panel"><div className="panel-header"><h2>Playoff Bracket</h2>{!t.champion && <button onClick={()=>updateTournament('playoff-round')}>Sim Other/Remaining Playoff Round</button>}</div><div className="panel-body bracket-grid">{t.playoffs.rounds.map((r,ri)=><div key={r.name}><h3>{r.name}</h3>{r.matches.map((m,mi)=><div key={mi}>{m.result ? <MatchResult match={m.result} userTeamId={userTeamId}/> : <div className={`match-card ${[m.teamA?.teamId,m.teamB?.teamId].includes(userTeamId)?'your-match-card':''}`}>{m.teamA?.shortName} vs {m.teamB?.shortName} {[m.teamA?.teamId,m.teamB?.teamId].includes(userTeamId) && <button onClick={()=>updateTournament('playoff-match',{roundIndex:ri,matchIndex:mi})}>Play / Sim Your Match</button>}</div>}</div>)}</div>)}</div></div>}
  {t.champion && <div className="champion-card">Champion: {t.champion.name}</div>}
  <div className="grid-2"><div className="panel"><div className="panel-header"><h2>Swiss Standings</h2></div><table><tbody>{sortStandings(t.swiss.standings).map(r=><tr key={r.teamId} className={r.teamId===userTeamId?'your-team-row':''}><td>{r.team.name}</td><td>{r.wins}-{r.losses}</td><td><span className={`status-${r.status}`}>{r.status}</span></td></tr>)}</tbody></table></div><div className="panel"><div className="panel-header"><h2>Event News / Results</h2></div><div className="panel-body match-grid">{t.swiss.rounds.flatMap(r=>r.matches).slice(-8).map((m,i)=><MatchResult key={i} match={m} userTeamId={userTeamId}/>)}</div></div></div>
  {summary && <div className="panel"><div className="panel-header"><h2>Event Summary</h2></div><div className="panel-body"><p>Champion: {summary.champion?.name} · Runner-up: {summary.runnerUp?.name} · Your record: {summary.userRecord.wins}-{summary.userRecord.losses} · Prize money: {formatMoney(summary.prizeMoneyEarned)} · Reputation: +{summary.reputationChange} · Ranking movement: {summary.rankingMovement}</p><p>Biggest upset: {summary.biggestUpset ? `${summary.biggestUpset.winner.shortName} over ${summary.biggestUpset.loser.shortName}` : 'None'} · MVP candidate: {summary.mvp?.gamertag || 'TBD'}</p></div></div>}
  {!userAlive && <div className="panel"><div className="panel-body">Your team has been eliminated. You can quickly simulate the rest of the event.</div></div>}
  </div>;
}
